import unittest


def triangulars(n):
    """
    The sequence of triangle numbers is generated by adding the natural numbers.
    So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
    The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    @param n: int - the length of triangular sequence
    """
    a = 1
    for i in range(2, n + 2):
        yield a
        a = a + i


class TriangularTest(unittest.TestCase):
    def test_triangulars(self):
        self.assertEqual(list(triangulars(7)), [1, 3, 6, 10, 15, 21, 28])


# unittest.main()
